### ISSUE TITLE
Export/import dsk/sma

### ISSUE THREAD

**Issue by kamelie1706** [benchmarko/CPCBasicTS#4]
It would be handy!

**Comment by benchmarko** [comment]
Importing DSK or ZIP is already possible. Use Drag&Drop on the CPC screen or the drop field in "Input". There you can also select a file for import. CPC files are extracted and put in "storage".

**Comment by kamelie1706** [comment]
Great! What about exporting? I have not found any online tool able to do that

**Comment by benchmarko** [comment]
Importing SNA is also possible now (0.1.9). CpcBasic will put it under storage. When selected, the BASIC source is extracted (assuming start address &170) and the memory, including the screen memory. Screen mode and colors are also set. Other parts like Z80 register are ignored.
Exporting will be a bit trickier because it must be valid hardware/software state for Z80 based emulators.

**Comment by kamelie1706** [comment]
Clear for sna but there should be no such problem for dsk export right?

**Comment by kamelie1706** [comment]
Kind of related : export in basic token file format

**Comment by benchmarko** [comment]
Download as tokenized BASIC was already possible. Now you can also export a file as DSK image (v0.1.13).

**Comment by kamelie1706** [comment]
Fantastic! For whatever reason I totally missed the export function...

**Comment by benchmarko** [comment]
Now you can also export multiple files from storage (v0.2.5).
